---
name: quality-check
on: push
jobs:
  run-check:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare
        run: make install
      - name: check
        run: |
          make check &&
          make lint &&
          make test
  upload-report:
    needs: run-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare
        run: make install
      - name: generate
        run: make coverage
      - name: report
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
